//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.24 at 08:03:12 PM IST 
//


package com.bhavna.student;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="totalMarks" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="averageMarks" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="result" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="percentage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "totalMarks",
    "averageMarks",
    "result",
    "percentage"
})
@XmlRootElement(name = "StudentResponse")
public class StudentResponse {

    @XmlElement(required = true)
    protected String totalMarks;
    @XmlElement(required = true)
    protected String averageMarks;
    @XmlElement(required = true)
    protected String result;
    @XmlElement(required = true)
    protected String percentage;

    /**
     * Gets the value of the totalMarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalMarks() {
        return totalMarks;
    }

    /**
     * Sets the value of the totalMarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalMarks(String value) {
        this.totalMarks = value;
    }

    /**
     * Gets the value of the averageMarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAverageMarks() {
        return averageMarks;
    }

    /**
     * Sets the value of the averageMarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAverageMarks(String value) {
        this.averageMarks = value;
    }

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResult(String value) {
        this.result = value;
    }

    /**
     * Gets the value of the percentage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPercentage() {
        return percentage;
    }

    /**
     * Sets the value of the percentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPercentage(String value) {
        this.percentage = value;
    }

}
